/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cache_CONSTANTS_H
#define cache_CONSTANTS_H

#include "cache_types.h"



class cacheConstants {
 public:
  cacheConstants();

};

extern const cacheConstants g_cache_constants;



#endif
